name: Deploy to Droplet
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # quick sanity check that the key parses
          ssh-keygen -y -f ~/.ssh/id_ed25519 > /dev/null
          # trust the host key so we don’t get prompted
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy main site
        run: |
          rsync -az --delete -e "ssh" \
            haleycse135.site/public_html/ \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/haleycse135.site/public_html/
          rsync -az --delete -e "ssh" \
            haleycse135.site/cgi-bin/ \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/haleycse135.site/cgi-bin/
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
            'set -euo pipefail; \
             sudo chown -R www-data:www-data /var/www/haleycse135.site/cgi-bin || true; \
             sudo chmod -R 755 /var/www/haleycse135.site/cgi-bin; \
             # Also place CGI scripts into the Apache ScriptAlias if present \
             if [ -d /usr/lib/cgi-bin ]; then \
               sudo rsync -az --delete /var/www/haleycse135.site/cgi-bin/ /usr/lib/cgi-bin/; \
               sudo chown -R www-data:www-data /usr/lib/cgi-bin; \
               sudo chmod -R 755 /usr/lib/cgi-bin; \
               # Relax auth on cgi-bin if a global BasicAuth is configured \
               if [ -d /etc/apache2/conf-available ]; then \
                 echo "<Directory /usr/lib/cgi-bin>\n    Options +ExecCGI\n    AddHandler cgi-script .cgi .pl\n    Require all granted\n</Directory>" | sudo tee /etc/apache2/conf-available/haley-cgi.conf >/dev/null; \
                 sudo a2enconf haley-cgi || true; \
                 sudo a2enmod cgi || true; \
                 sudo systemctl reload apache2 || sudo service apache2 reload || true; \
               fi; \
             fi; \
             mkdir -p /var/www/haleycse135.site/src-build; \
             cd /var/www/haleycse135.site/src-build; \
             rm -f c-hello-html-world.cgi c-hello-json-world.cgi c-env.cgi c-get-echo.cgi c-post-echo.cgi c-general-request-echo.cgi c-sessions-1.cgi c-sessions-2.cgi c-destroy-session.cgi; \
             gcc -O2 -o c-hello-html-world.cgi ../public_html/src/c-hello-html-world.c; \
             gcc -O2 -o c-hello-json-world.cgi ../public_html/src/c-hello-json-world.c; \
             gcc -O2 -o c-env.cgi ../public_html/src/c-env.c; \
             gcc -O2 -o c-get-echo.cgi ../public_html/src/c-get-echo.c; \
             gcc -O2 -o c-post-echo.cgi ../public_html/src/c-post-echo.c; \
             gcc -O2 -o c-general-request-echo.cgi ../public_html/src/c-general-request-echo.c; \
             mv -f *.cgi /var/www/haleycse135.site/cgi-bin/; \
             if [ -d /usr/lib/cgi-bin ]; then \
               sudo rsync -az --delete /var/www/haleycse135.site/cgi-bin/ /usr/lib/cgi-bin/; \
             fi; \
             sudo chown -R www-data:www-data /var/www/haleycse135.site/cgi-bin; \
             sudo chmod -R 755 /var/www/haleycse135.site/cgi-bin; \
             perl -v >/dev/null 2>&1 || true'

      - name: Deploy collector
        run: |
          rsync -az --delete -e "ssh" \
            collector.haleycse135.site/public_html/ \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/collector.haleycse135.site/public_html/

      - name: Deploy reporting
        run: |
          rsync -az --delete -e "ssh" \
            reporting.haleycse135.site/public_html/ \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/reporting.haleycse135.site/public_html/

      - name: Smoke test
        run: |
          curl -f https://haleycse135.site/ > /dev/null
          curl -f https://collector.haleycse135.site/ > /dev/null
          curl -f https://reporting.haleycse135.site/ > /dev/null
